# Generated by Django 4.1.7 on 2023-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('rooms', models.IntegerField(null=True)),
                ('baths', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
