# Generated by Django 4.1.7 on 2023-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0002_asset_date_asset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='use',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
