# Generated by Django 4.1.7 on 2023-04-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0005_landplot_alter_house_phone_alter_house_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='landplot',
            name='image2',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='image3',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='image4',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='image5',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
