# Generated by Django 4.1.7 on 2023-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0006_landplot_image2_landplot_image3_landplot_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='house',
            name='image4',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='house',
            name='image5',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
