# Generated by Django 4.1.7 on 2023-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0007_house_image2_house_image3_house_image4_house_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='MoreDescription',
            field=models.CharField(default='', max_length=255),
        ),
    ]
