# Generated by Django 4.2.2 on 2023-06-24 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0009_alter_house_moredescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('use', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('image2', models.ImageField(default='', upload_to='shop/images')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
