# Generated by Django 4.2.2 on 2023-06-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0010_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='carImage1',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='image2',
            new_name='carImage2',
        ),
        migrations.RenameField(
            model_name='landplot',
            old_name='image',
            new_name='plotImage1',
        ),
        migrations.RenameField(
            model_name='landplot',
            old_name='image2',
            new_name='plotImage2',
        ),
        migrations.RenameField(
            model_name='landplot',
            old_name='image3',
            new_name='plotImage3',
        ),
        migrations.RenameField(
            model_name='landplot',
            old_name='image4',
            new_name='plotImage4',
        ),
        migrations.RenameField(
            model_name='landplot',
            old_name='image5',
            new_name='plotImage5',
        ),
    ]
