# Generated by Django 4.2.2 on 2023-06-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0011_rename_image_car_carimage1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='MoreDescription',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='landplot',
            name='MoreDescription',
            field=models.TextField(default='', max_length=255),
        ),
    ]
