# Generated by Django 4.2.2 on 2023-06-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0013_car_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carImage3',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
